.TH infinitetux 7
.SH NAME
infinitetux \-A more compatible version of Infinite Mario.
.SH SYNOPSIS
.B infinitetux
.TP
.SH DESCRIPTION
.B infinitetux
A more compatible version of Infinite Mario
.SH OPTIONS
.TP
f  Full screen mode
Example:

infintiemariobros f
.SH DISCLAIMER
use at your own risk.
.SH AUTHORS 
Written by cflewis
