.TH INFINITETUX 6
.SH NAME
infinitetux \- Infinite Tux is a 2D platformer game inspired by Infinite Mario.
.SH SYNOPSIS
.SH 
.B infinitetux
.SH 
.SH	DESCRIPTION
.SH 
.SS Infinite Tux is a 2D platformer game inspired by Infinite
.SS Mario. The game is procedurally generated every time it is replayed so
.SS you always play a different game. The game Infinite Mario was taken
.SS and all of the proprietary assets were repalced with open source
.SS assets.
.SH 
.SS The game does not have gamepad support so it is played with the
.SS keyboard. One can play the game with a gamepad using a program like
.SS qjoypad. qjoypad takes input from a gamepad or joystick and translates
.SS it into key strokes or mouse actions, letting you control any X Windows
.SS program with your game controller.
.SH 
.SH PLAYING THE GAME
.SH 
.SS LEFT ARROW	-Moves Tux to the left.
.SS RIGHT ARROW	-Moves Tux to the right.
.SS DOWN ARROW	-Makes Tux duck.
.SS A			-NES (B) button. Run faster, pick up shells, and fire.
.SS S			-NES (A) button. Jump
.SS ESC			-Closes the game.
.SH 
.SH DISCLAIMER
.SH 
use at your own risk.
.SH 
.SH AUTHORS 
.SH 
Written by Markus Persson with contributions from Chris Lewis and\
 Pedro Pena (qbancoffee@yahoo.com)
